### ISSUE TITLE
Reproduce the result

### ISSUE THREAD

**Issue by Shakib-IO** [EmorZz1G/PatchAD#1]
Hi @EmorZz1G @yyysjz1997 
I read your PatchAD paper. Great work!!
I would like to reproduce the result. It would be great if you could provide the instruction on the README(requirements.txt, dataset, etc).

Thank you

**Comment by EmorZz1G** [comment]
Thank you for your kind comment. 
The instruction is coming soon. Due to the almost same experiment configuration, you can refer the previous work first, e.g DCdetector and Anomaly Transformer. You can search them in github. Hope this helps you.
