### ISSUE TITLE
Request for a files

### ISSUE THREAD

**Issue by zhangtt2024** [EmorZz1G/PatchAD#2]
Hello, during the reproduction process, I encountered the following error: "No such file or directory: '/share/home/202220143416/time_series_data/dc_detector/MSL/MSL_train.npy' ". Could you provide this folder named " share" ? Thank you very much.

**Comment by EmorZz1G** [comment]
Thank you for your attention. We have updated the readme file, and now you can download the dataset. Please update the `file_path` accordingly to proceed with the default operation.

## Datasets
You can download all datasets [here](https://drive.google.com/drive/folders/1RaIJQ8esoWuhyphhmMaH-VCDh-WIluRR?usp=sharing).
(Thanks for [DCdetector](https://github.com/DAMO-DI-ML/KDD2023-DCdetector/blob/main/readme.md) repo and its authors.)
