### ISSUE TITLE
Inconsistent between the paper and the code

### ISSUE THREAD

**Issue by richard-tang199** [EmorZz1G/PatchAD#5]
![image](https://github.com/user-attachments/assets/8f2fac78-6543-4801-80a1-a56cf91fc9d8)
In your paper, you describe the anomaly score is calculated as the KL divergence between two views. In your code, the anomaly score is calculated as the weight summation of reconstruction errors and KL divergence. However, you set the weight of KL divergence to zero, and the anomaly score is equal to the reconstruction error. This is absolutely different from your paper.

**Comment by EmorZz1G** [comment]
Thank you for your question. Currently, for different types of anomalies, the cont_beta parameter needs to be adjusted. The 0 you mentioned should be the default setting. Later, we will update arXiv to ensure that the paper is consistent with the code. Thank you again for your valuable question!
